version: '3'

services:
  api-samartranking:
    user: node
    build: .
    container_name: api-samartranking
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    ports:
      - '3000:3000'
      - '5555:5555'
    entrypoint: "sh ./.docker/entrypoint.sh"